name: Terraform CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
      - name: Check terraform format
        run: terraform version